//require请求一个config的js文件
require.config({
	baseUrl:"/",
	paths:{
		"header":"module/header",
		"footer":"module/footer",
		"jquery":"libs/jquery/jquery-1.11.3",
		"bootstrap":"libs/bootstrap/js/bootstrap",
		"tools":"libs/tools"
	},
	//垫片，谁依赖谁，谁就写在上面
	shim:{
		"bootstrap":{
			deps:["jquery"]
		}
	}
})